# 8. 基于MindSpore构造激活函数
本实验主要介绍使用MindSpore实现神经网络中的ReLU激活函数，使用自定义数据进行测试。

# 1. 实验目的
- 了解激活函数在人工神经网络中的作用。
- 掌握如何使用MindSpore构造ReLU激活函数，并使用自定义数据进行测试。

# 2. ReLU激活函数知识点介绍
激活函数是在人工神经网络的神经元上运行的函数，负责将神经元的输入映射到输出端。  
激活函数对于神经网络模型去学习、理解复杂和非线性的函数具有十分重要的意义，它们将非线性特性引入到网络中。如图所示，在神经元中，输入（inputs）通过加权、求和后，还被作用在一个函数上，这个函数就是激活函数。  
![](Figures/fig_001.png)  
如果不使用激活函数，神经网络中每一层的输入都是上一层输出的线性函数，无论神经网络有多少层，输出都是输入的线性组合，这种情况网络会退化为最原始的感知机。使用非线性激活函数是为了增加神经网络模型的非线性因素，使网络更加强大，可以学习更加复杂的事物。  
整流线性单元（Rectified linear unit, ReLU）是现代神经网络中最常用的激活函数，是大多数前馈神经网络默认使用的激活函数，函数表达式如下：   
$$
f(x) =\max(0,x)
$$  
函数图像：  
![](Figures/fig_002.png)

# 3. 实验环境
在动手进行实践之前，需要注意以下几点：
* 确保实验环境正确安装，包括安装MindSpore。安装过程：首先登录[MindSpore官网安装页面](https://www.mindspore.cn/install)，根据安装指南下载安装包及查询相关文档。同时，官网环境安装也可以按下表说明找到对应环境搭建文档链接，根据环境搭建手册配置对应的实验环境。
* 推荐使用交互式的计算环境Jupyter Notebook，其交互性强，易于可视化，适合频繁修改的数据分析实验环境。
* 实验也可以在华为云一站式的AI开发平台ModelArts上完成。
* 推荐实验环境：MindSpore版本=2.4；Python环境=3.9。


|  硬件平台 |  操作系统  | 软件环境 | 开发环境 | 环境搭建链接 |
| :-----:| :----: | :----: |:----:   |:----:   |
| CPU | Windows-x64 | MindSpore2.4 Python3.9 | JupyterNotebook |[MindSpore环境搭建实验手册第二章2.1节和第三章3.1节](./MindSpore环境搭建实验手册.docx)|
| GPU CUDA 10.1|Linux-x86_64| MindSpore2.4 Python3.9 | JupyterNotebook |[MindSpore环境搭建实验手册第二章2.2节和第三章3.1节](./MindSpore环境搭建实验手册.docx)|
| Ascend 910  | Linux-x86_64| MindSpore2.4 Python3.9 | JupyterNotebook |[MindSpore环境搭建实验手册第四章](./MindSpore环境搭建实验手册.docx)|

# 4. 数据处理
## 4.1 数据准备
自定义张量（Tensor）数据进行测试。  
Tensor本质上是一个多维数组（multidimensional array），使用  Tensor的目的是能够创造更高维度的矩阵、向量。  
本实验中定义的张量数据 Tensor 格式如下所示：
$$
[<Array_1>,<Array_2>,\cdots, <Array_n>]
$$  
测试数据定义为： 
  
`[[ 1.0,  2.0, -4.0,  1.3], [-1.3,  2.0,  1.0, -6.0]]`
## 4.2 数据加载
代码：

In [1]:
# 引入mindspore
import mindspore as ms
# 引入神经网络模块
from mindspore.nn import Cell
# 引入MindSpore的ReLU函数接口
from mindspore.nn import ReLU
from mindspore import dtype as mstype
# 定义张量数据
tensor = ms.Tensor([[ 1.0,  2.0, -4.0,  1.3],
                    [-1.3,  2.0,  1.0, -6.0]], dtype=mstype.float32)

# 5. 模型构建

In [2]:
# 继承Cell类，构造ReLU函数
class My_Relu(Cell):
    def __init__(self):
        super(My_Relu, self).__init__()
    def construct(self, x):        
        x[x<0] = 0.0  # 换表达方式:用if else改写relu实现      
        
        return x

# 6. 模型测试
使用自定义数据对ReLU函数进行测试，观察函数实现是否正确。

In [3]:
# 实例化ReLU函数
my_relu = My_Relu()
# 输出
output = my_relu(tensor)
# 打印输出
relu = ReLU()
output_2 = relu(tensor)
print('自定义ReLU函数\n', output)
print('接口ReLU函数\n', output_2)

自定义ReLU函数
 [[1.  2.  0.  1.3]
 [0.  2.  1.  0. ]]
接口ReLU函数
 [[1.  2.  0.  1.3]
 [0.  2.  1.  0. ]]


# 基于MindSpore构造常见激活函数(附)

在Python中，我们可以使用NumPy库来构建常见的激活函数。NumPy是一个强大的科学计算模块，它包含了很多的数学函数，可以用来快速方便地进行各种数学运算。

以下是一些常见的激活函数以及它们的Python实现：

**1、线性函数（Linear Function）：**

这是一个线性的函数，它的输出和输入是线性关系。在MindS'pore中，我们可以直接使用数组操作来实现这个函数。

In [4]:
import mindspore as ms
 
def linear(x):
    return x

**2、双曲线正切激活函数（Tanh）：**

双曲线正切函数在MindSpore中可以通过ops.tanh函数来实现。

In [5]:
import numpy as np
import mindspore
from mindspore import Tensor, ops
 
def tanh(x):
    return ops.tanh(x)

input = Tensor(np.array([1, 2, 3, 4, 5]), mindspore.float32)
output = tanh(input)
print(output)

[0.7615942 0.9640276 0.9950557 0.9993442 1.0000098]


**3、反正切激活函数（Arctan）：**

反正切函数在MindSpore中可以通过ops.arctan函数来实现。

In [6]:
import mindspore
from mindspore import Tensor, ops
import numpy as np
 
def arctan(x):
    return ops.arctan(x)

x = Tensor(np.array([1.0, 0.0]), mindspore.float32)
output = arctan(x)
print(output)

[0.7853982 0.       ]


**4、自然指数激活函数（Exp）：**

自然指数函数在MindSpore中可以通过ops.exp函数来实现。

In [7]:
import mindspore
import numpy as np
from mindspore import Tensor, ops
 
def exp(x):
    return ops.exp(x)

input = Tensor(np.array([0.0, 1.0, 3.0]), mindspore.float32)
output = exp(input)
print(output)

[ 1.         2.7182798 20.085548 ]


**5、sigmoid激活函数：**

Sigmoid函数在MindSpore中可以通过1 / (1 + ops.exp(-x))来实现。

In [8]:
import mindspore
import numpy as np
from mindspore import Tensor, ops
 
def sigmoid(x):
    return 1 / (1 + ops.exp(-x))

input = Tensor(np.array([0.0, 1.0, 3.0]), mindspore.float32)
output = sigmoid(input)
print(output)

[0.5        0.7310589  0.95257413]


**6、ReLU激活函数：**

ReLU（Rectified Linear Unit）函数在MindSpore中可以通过ops.maximum(x, 0)来实现。

In [9]:
import mindspore
import numpy as np
from mindspore import Tensor, ops

def relu(x, other):
    return ops.maximum(x, other)

input = Tensor(np.array([1.0, 5.0, 3.0]), mindspore.float32)
other = Tensor(np.array([4.0, 2.0, 6.0]), mindspore.float32)
output = relu(input, other)
print(output)

[4. 5. 6.]


**7、Leaky ReLU激活函数：**

Leaky ReLU是ReLU的一个变体，它在输入是负数的时候不是直接置零，而是给予一个小的斜率。在MindSpore中，我们可以通过条件语句来实现这个函数。

In [10]:
import mindspore
import numpy as np
from mindspore import Tensor, ops
 
def leaky_relu(x, alpha=0.1):
    return ops.maximum(x, alpha*x)

inputs = Tensor(np.array([-1.0, 2.0, 5.0, 3.0]), mindspore.float32)
output = leaky_relu(inputs)
print(output)

[-0.1  2.   5.   3. ]


**8、Softmax激活函数：**

Softmax函数通常用于分类问题，它可以将输入向量归一化，使得所有的输出值在0和1之间，且和为1。在MindSpore中，我们可以通过如下方式来实现这个函数。

In [11]:
import mindspore
import numpy as np
from mindspore import Tensor, ops
 
def softmax(x):
    exp_x = ops.exp(x)
    return exp_x / ops.sum(exp_x, dim=-1, keepdim=True)

input = Tensor(np.array([0.0, 1.0, 3.0]), mindspore.float32)
output = softmax(input)
print(output)

[0.04201005 0.11419506 0.8437948 ]
